/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemPackage;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NishanV
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_customer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_cashier = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_AddCustomer = new javax.swing.JButton();
        jButton_AddCashier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_RemoveCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_AddVideo = new javax.swing.JButton();
        jButton_RemoveCashier = new javax.swing.JButton();
        jButton_ireport = new javax.swing.JButton();
        jButton_removeVideo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_videos = new javax.swing.JTable();
        jButton_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "First Name", "Last Name", "Address", "Phone", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_customer);

        jTable_cashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "First Name", "Last Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_cashier);

        jButton_AddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1457975586_User.png"))); // NOI18N
        jButton_AddCustomer.setText("Add Customer");
        jButton_AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddCustomerActionPerformed(evt);
            }
        });

        jButton_AddCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1457975586_User.png"))); // NOI18N
        jButton_AddCashier.setText("Add Cashier");
        jButton_AddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddCashierActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Admin Panel");

        jButton_RemoveCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-remove-icon.png"))); // NOI18N
        jButton_RemoveCustomer.setText("Remove Customer");
        jButton_RemoveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveCustomerActionPerformed(evt);
            }
        });

        jLabel2.setText("Registered Customers:");

        jLabel3.setText("Registered Cashiers:");

        jButton_AddVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/movie-track-add-icon.png"))); // NOI18N
        jButton_AddVideo.setText("Add Video");
        jButton_AddVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddVideoActionPerformed(evt);
            }
        });

        jButton_RemoveCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-remove-icon.png"))); // NOI18N
        jButton_RemoveCashier.setText("Remove Cashier");
        jButton_RemoveCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveCashierActionPerformed(evt);
            }
        });

        jButton_ireport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clipboard_report_form_checklist_business_plan_sheet_file_note_pad_paper_page_document_planning_check_list_survey_questionnaire_flat_design_icon-512.png"))); // NOI18N
        jButton_ireport.setText("i-Reports");
        jButton_ireport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ireportActionPerformed(evt);
            }
        });

        jButton_removeVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/movie_track_remove.png"))); // NOI18N
        jButton_removeVideo.setText("Remove Video");
        jButton_removeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeVideoActionPerformed(evt);
            }
        });

        jTable_videos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "video ID", "Title", "Quantity", "Price per 7 Days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_videos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable_videos);
        if (jTable_videos.getColumnModel().getColumnCount() > 0) {
            jTable_videos.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton_logout.setText("Logout");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jLabel4.setText("Videos in Store:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_AddCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AddVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_ireport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_RemoveCashier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_RemoveCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_removeVideo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton_logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane3)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_logout)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_AddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_RemoveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_AddCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_RemoveCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_AddVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_removeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_ireport, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddCashierActionPerformed
        RegisterNewCashier rgCashier = new RegisterNewCashier();
        rgCashier.setVisible(true);
    }//GEN-LAST:event_jButton_AddCashierActionPerformed

    private void jButton_AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddCustomerActionPerformed
        RegisterNewCustomer regCust = new RegisterNewCustomer();
        regCust.setVisible(true);
    }//GEN-LAST:event_jButton_AddCustomerActionPerformed

    private void jButton_RemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveCustomerActionPerformed
        int row=jTable_customer.getSelectedRow();
        String memberId=(jTable_customer.getModel().getValueAt(row,0).toString());
        DBConnect connect = new DBConnect();
        if(memberId.equals(""))
        {
            JOptionPane.showMessageDialog(null, "No selected data");
        }else{
            try{
                String query = "delete from members where memberId = '"+memberId+"'";
                connect.st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "User Removed!!");
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton_RemoveCustomerActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DBConnect connectCust = new DBConnect();
        DBConnect connectCashier = new DBConnect();
        DBConnect connectVideos = new DBConnect();
        DefaultTableModel custTable = (DefaultTableModel) jTable_customer.getModel();
        DefaultTableModel cashierTable = (DefaultTableModel) jTable_cashier.getModel();
        DefaultTableModel videoTable = (DefaultTableModel) jTable_videos.getModel();
        int custTableRowCount = custTable.getRowCount();
        int cashierTableRowCount = cashierTable.getRowCount();
        int videoTableRowCount = videoTable.getRowCount();
        for(int i = custTableRowCount - 1; i >=0; i--)
            custTable.removeRow(i);
        for(int i = cashierTableRowCount - 1; i >=0; i--)
            cashierTable.removeRow(i);
        for(int i = videoTableRowCount - 1; i >=0; i--)
            videoTable.removeRow(i);
        String queryCust = "Select * from members where type = 2";
        String queryCashier = "Select * from members where type = 1";
        String queryVideos = "select * from videos";
        try{
            connectCust.rs = connectCust.st.executeQuery(queryCust);
            connectCashier.rs = connectCashier.st.executeQuery(queryCashier);
            connectVideos.rs = connectVideos.st.executeQuery(queryVideos);
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        try{
            while(connectCust.rs.next())
                    custTable.addRow(new Object[]{connectCust.rs.getString("memberId"), connectCust.rs.getString("fname"), connectCust.rs.getString("lname"), connectCust.rs.getString("address"), connectCust.rs.getString("phone"), connectCust.rs.getString("pwd")});
            while(connectCashier.rs.next())
                    cashierTable.addRow(new Object[]{connectCashier.rs.getString("memberId"), connectCashier.rs.getString("fname"), connectCashier.rs.getString("lname"), connectCashier.rs.getString("pwd")});
            while(connectVideos.rs.next())
                    videoTable.addRow(new Object[]{connectVideos.rs.getString("videoId"), connectVideos.rs.getString("title"), connectVideos.rs.getString("qty"), connectVideos.rs.getString("pricePer7d")});
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton_AddVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddVideoActionPerformed
        AddVideoDetails addVid = new AddVideoDetails(this, rootPaneCheckingEnabled);
        addVid.setVisible(true);
    }//GEN-LAST:event_jButton_AddVideoActionPerformed

    private void jButton_RemoveCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveCashierActionPerformed
        int row=jTable_cashier.getSelectedRow();
        String memberId=(jTable_cashier.getModel().getValueAt(row,0).toString());
        DBConnect connect = new DBConnect();
        if(memberId.equals(""))
        {
            JOptionPane.showMessageDialog(null, "No selected data");
        }else{
            try{
                String query = "delete from members where memberId = '"+memberId+"'";
                connect.st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "User Removed!!");
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton_RemoveCashierActionPerformed

    private void jButton_ireportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ireportActionPerformed
        report ireport = new report();
        ireport.setVisible(true);        
    }//GEN-LAST:event_jButton_ireportActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        this.dispose();
        MainLogin login = new MainLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_removeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeVideoActionPerformed
        int row=jTable_videos.getSelectedRow();
        String videoId=(jTable_videos.getModel().getValueAt(row,0).toString());
        DBConnect connect = new DBConnect();
        if(videoId.equals(""))
        {
            JOptionPane.showMessageDialog(null, "No selected data");
        }else{
            try{
                String query = "delete from videos where videoId = '"+videoId+"'";
                connect.st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Video Removed!!");
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton_removeVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddCashier;
    private javax.swing.JButton jButton_AddCustomer;
    private javax.swing.JButton jButton_AddVideo;
    private javax.swing.JButton jButton_RemoveCashier;
    private javax.swing.JButton jButton_RemoveCustomer;
    private javax.swing.JButton jButton_ireport;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_removeVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_cashier;
    private javax.swing.JTable jTable_customer;
    private javax.swing.JTable jTable_videos;
    // End of variables declaration//GEN-END:variables
}
