/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemPackage;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NishanV
 */
public class PlaceOrder extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrder
     */
    String custName;
    String memberId;
    double totalAmount = 0.0;
    public PlaceOrder(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public PlaceOrder(java.awt.Frame parent, boolean modal, String pcustName, String pmemberId) {
       // super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        custName = pcustName;
        memberId = pmemberId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_custName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_memberId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_addItem = new javax.swing.JButton();
        jTextField_VideoId = new javax.swing.JTextField();
        jTextField_AdditionalTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_totAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_Qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_selectVideos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField_custName.setEditable(false);
        jTextField_custName.setText("Customer");

        jLabel1.setText("Customer Name:");

        jLabel2.setText("Member ID:");

        jTextField_memberId.setEditable(false);
        jTextField_memberId.setText("Customer ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("New Order");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Video ID", "Title", "Quantity", "Due Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_addItem.setText("Add");
        jButton_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addItemActionPerformed(evt);
            }
        });

        jTextField_AdditionalTime.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total (Rs):");

        jTextField_totAmount.setEditable(false);
        jTextField_totAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_totAmount.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_totAmount.setText("Total Amount");

        jLabel5.setText("Video ID:");

        jLabel6.setText("Additional Days:");

        jTextField_Qty.setText("1");

        jLabel7.setText("Qty:");

        jButton_selectVideos.setText("Select Video");
        jButton_selectVideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectVideosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_memberId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_custName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_VideoId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_AdditionalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_selectVideos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_totAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_memberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField_totAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_VideoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_AdditionalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton_selectVideos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField_custName.setText(this.custName);
        jTextField_memberId.setText(this.memberId);
    }//GEN-LAST:event_formWindowOpened

    private void jButton_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addItemActionPerformed
        DBConnect connect = new DBConnect();
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        Date today = new Date();
        String videoId = jTextField_VideoId.getText();
        String qty = jTextField_Qty.getText();
        String additional = jTextField_AdditionalTime.getText();
        boolean videoIdExists = true;
        String qtyAvailable = null;
        double pricePer7D = 0.0;
        double pricePerAddD = 0.0;
        double amount = 0.0;
        String videoTitle = null;
        String query = "select * from videos where videoId = '"+videoId+"'";
        try{
            connect.rs = connect.st.executeQuery(query);
            connect.rs.next();
            videoTitle = connect.rs.getString("title");
        }catch(Exception e){
        }
        if(videoId.equals("") || videoId.equals(null) || qty.equals("") || qty.equals(null) || additional.equals("") || additional.equals(null)){
            JOptionPane.showMessageDialog(null, "Please Enter All Details !");
        }
        else{
            query = "select * from videos where videoId = "+videoId;
            try{
                connect.rs = connect.st.executeQuery(query);
                if(connect.rs.next() == false)
                    videoIdExists = false;
                else{
                    //connect.rs.next();
                    qtyAvailable = connect.rs.getString("qty");
                    pricePer7D = Double.parseDouble(connect.rs.getString("pricePer7d"));
                    pricePerAddD = Double.parseDouble(connect.rs.getString("addPricePerD"));
                    videoTitle = connect.rs.getString("title");
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            
            if(videoIdExists == false)
                JOptionPane.showMessageDialog(null, "Invalid Video ID !!");
            else if(Integer.parseInt(qtyAvailable) < Integer.parseInt(qty)){
                if(qtyAvailable.equals("0"))
                    JOptionPane.showMessageDialog(null, "The Video You requesting is Currently Out Of Stock!");
                else
                    JOptionPane.showMessageDialog(null, "Order Couldn't Proceed. We currently have only "+qtyAvailable+" of Units Only.");
            }
            else if(Integer.parseInt(qty) <= 0){
                JOptionPane.showMessageDialog(null, "Quantity must be more than Zero. Order Not Proceeded!");
            }
            else{
                for(int i = table.getRowCount() - 1; i >=0; i--)
                    table.removeRow(i);
                SimpleDateFormat formattedDate = new SimpleDateFormat("yyyy-MM-dd");
                Calendar c = Calendar.getInstance();
                String todayDate = (String) formattedDate.format(c.getTime());
                //JOptionPane.showMessageDialog(null, "Today is "+(String) formattedDate.format(c.getTime()));
                c.add(Calendar.DATE, (7+Integer.parseInt(additional)));  // number of days to add      
                String dueDate = (String)(formattedDate.format(c.getTime()));
                amount = Integer.parseInt(qty)*(pricePer7D+(pricePerAddD*Integer.parseInt(additional)));
                query = "insert into orders (memberId, qty, videoId, title, dueDate, amount, orderedDate, returned) values ("+this.memberId+", "+qty+" ,"+videoId+", '"+videoTitle+"', '"+dueDate+"', "+amount+",'"+todayDate+"', 'no')";
                int newQty = Integer.parseInt(qtyAvailable)-Integer.parseInt(qty);
                try{
                    connect.st.executeUpdate(query);
                    query = "select * from orders where memberId = "+this.memberId+" and returned = 'no'";
                    connect.rs = connect.st.executeQuery(query);
                    while(connect.rs.next())
                        table.addRow(new Object[]{connect.rs.getString("videoId"), connect.rs.getString("title"), connect.rs.getString("qty"), connect.rs.getString("dueDate"), connect.rs.getString("amount")});
                    query = "update videos set qty = "+newQty+" where videoId = "+videoId;
                    connect.st.executeUpdate(query);
                    totalAmount = totalAmount+amount;
                    jTextField_totAmount.setText(String.valueOf(totalAmount));
                }catch(Exception e){
                }
            }
        }
    }//GEN-LAST:event_jButton_addItemActionPerformed

    private void jButton_selectVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectVideosActionPerformed
        VideoDetails videoDetails = new VideoDetails(1, Integer.parseInt(this.memberId), "Close");
        videoDetails.setVisible(true);
    }//GEN-LAST:event_jButton_selectVideosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlaceOrder dialog = new PlaceOrder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addItem;
    private javax.swing.JButton jButton_selectVideos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_AdditionalTime;
    private javax.swing.JTextField jTextField_Qty;
    private javax.swing.JTextField jTextField_VideoId;
    private javax.swing.JTextField jTextField_custName;
    private javax.swing.JTextField jTextField_memberId;
    private javax.swing.JTextField jTextField_totAmount;
    // End of variables declaration//GEN-END:variables
}
